# This is a basic workflow to help you get started with Actions

name: Update

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get Versions
        run: |
          OLD_VER=$(grep -oP 'PB_VERSION=+\K.+' Dockerfile)
          [ -z $OLD_VER ] && echo "Could not acquire old version!" && exit 1
          
          NEW_VER=$(curl 'https://api.github.com/repos/pocketbase/pocketbase/tags' | jq -r '.[0].name' | grep -oP 'v+\K.+')
          [ -z $NEW_VER ] && echo "Could not acquire new version!" && exit 1
          
          echo "OLD_VER=$OLD_VER" >> $GITHUB_ENV
          echo "NEW_VER=$NEW_VER" >> $GITHUB_ENV
          

      # Runs a set of commands using the runners shell
      - name: Update Pocketbase
        if: ${{ env.OLD_VER != env.NEW_VER }}
        run: |
          sed -i 's/${{ env.OLD_VER }}/${{ env.NEW_VER }}/' Dockerfile
          git config --global user.name ${{ secrets.GIT_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git add -A
          git commit -m '[auto] Update Pocketbase from ${{ env.OLD_VER }} to ${{ env.NEW_VER }}' -m 'https://github.com/pocketbase/pocketbase/releases/tag/v${{ env.NEW_VER }}'
          git push
